# Site settings
title: Castillo Sings, Everybody Can Sing!
email: jazzvocalistme@gmail.com
url: https://www.castillosings.com
description: "Singing teacher and jazz vocalist established in Berlin since 2012. - Gesangslehrer und Jazz Sänger etabliert in Berlin seit 2012. Singing lessons, music theory, vocal coach. - Gesangsunterricht, Musiktheorie, Gesangslehrer."


  

# Footer settings
footer: Castillo Sings

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jazzvocalistme
  - title: facebook
    url: https://www.facebook.com/CastilloSingingTeacher/
  

# Build settings
markdown: kramdown
permalink: pretty

# Yes Future !
future: true
